title: "HC26 Senior Project — Jonah Smith"
description: "Proposal for my Senior Project"

url: "https://<JonahSmith25>.github.io"
baseurl: "/HC26-Smith-Jonah-Senior-Project"

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-seo-tag

remote_theme: pages-themes/midnight@v0.2.0  
